### ISSUE TITLE
Create file to translate White paper for Brazilian Portugues. 

### ISSUE THREAD

**Issue by EvertonMelo** [aragon/docs#2]
Please, 

I really admire your work, I want to contribute to it.

create the white paper file in Portugues do Brasil,
just creating the same in latex I can modify it to the described idimo.
if you want, I can start translating tb into Spanish

**Comment by EvertonMelo** [comment]
@luisivan 

you can help me?

**Comment by EvertonMelo** [comment]
you have no interest.

**Comment by luisivan** [comment]
A thousands apologies @evertonmelo, I just saw this.
Right now we don't have bandwidth to keep multiple languages, but thanks a lot for the offering!!
